// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// C_extract_window
NumericMatrix C_extract_window(NumericMatrix r, IntegerVector w, IntegerVector idx);
RcppExport SEXP _MultiscaleDEM_C_extract_window(SEXP rSEXP, SEXP wSEXP, SEXP idxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type r(rSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type w(wSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type idx(idxSEXP);
    rcpp_result_gen = Rcpp::wrap(C_extract_window(r, w, idx));
    return rcpp_result_gen;
END_RCPP
}
// subset_mat_rows
NumericMatrix subset_mat_rows(NumericMatrix x, LogicalVector idx);
RcppExport SEXP _MultiscaleDEM_subset_mat_rows(SEXP xSEXP, SEXP idxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type idx(idxSEXP);
    rcpp_result_gen = Rcpp::wrap(subset_mat_rows(x, idx));
    return rcpp_result_gen;
END_RCPP
}
// C_OLS_params
NumericVector C_OLS_params(arma::mat X, arma::mat Y);
RcppExport SEXP _MultiscaleDEM_C_OLS_params(SEXP XSEXP, SEXP YSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Y(YSEXP);
    rcpp_result_gen = Rcpp::wrap(C_OLS_params(X, Y));
    return rcpp_result_gen;
END_RCPP
}
// C_OLS_resid
NumericVector C_OLS_resid(arma::mat X, arma::mat Y);
RcppExport SEXP _MultiscaleDEM_C_OLS_resid(SEXP XSEXP, SEXP YSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Y(YSEXP);
    rcpp_result_gen = Rcpp::wrap(C_OLS_resid(X, Y));
    return rcpp_result_gen;
END_RCPP
}
// C_multiscale2
NumericMatrix C_multiscale2(NumericMatrix r, IntegerVector w, NumericMatrix X, bool na_rm);
RcppExport SEXP _MultiscaleDEM_C_multiscale2(SEXP rSEXP, SEXP wSEXP, SEXP XSEXP, SEXP na_rmSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type r(rSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type w(wSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< bool >::type na_rm(na_rmSEXP);
    rcpp_result_gen = Rcpp::wrap(C_multiscale2(r, w, X, na_rm));
    return rcpp_result_gen;
END_RCPP
}
// C_multiscale1
NumericVector C_multiscale1(NumericMatrix r, IntegerVector w, NumericMatrix X, bool na_rm);
RcppExport SEXP _MultiscaleDEM_C_multiscale1(SEXP rSEXP, SEXP wSEXP, SEXP XSEXP, SEXP na_rmSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type r(rSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type w(wSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< bool >::type na_rm(na_rmSEXP);
    rcpp_result_gen = Rcpp::wrap(C_multiscale1(r, w, X, na_rm));
    return rcpp_result_gen;
END_RCPP
}
// C_WoodEvans
NumericMatrix C_WoodEvans(NumericVector z, NumericMatrix X_full, bool na_rm, size_t ni, size_t nw);
RcppExport SEXP _MultiscaleDEM_C_WoodEvans(SEXP zSEXP, SEXP X_fullSEXP, SEXP na_rmSEXP, SEXP niSEXP, SEXP nwSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type z(zSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X_full(X_fullSEXP);
    Rcpp::traits::input_parameter< bool >::type na_rm(na_rmSEXP);
    Rcpp::traits::input_parameter< size_t >::type ni(niSEXP);
    Rcpp::traits::input_parameter< size_t >::type nw(nwSEXP);
    rcpp_result_gen = Rcpp::wrap(C_WoodEvans(z, X_full, na_rm, ni, nw));
    return rcpp_result_gen;
END_RCPP
}
// C_AdjSD
NumericVector C_AdjSD(NumericVector z, NumericMatrix X_full, bool na_rm, size_t ni, size_t nw);
RcppExport SEXP _MultiscaleDEM_C_AdjSD(SEXP zSEXP, SEXP X_fullSEXP, SEXP na_rmSEXP, SEXP niSEXP, SEXP nwSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type z(zSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X_full(X_fullSEXP);
    Rcpp::traits::input_parameter< bool >::type na_rm(na_rmSEXP);
    Rcpp::traits::input_parameter< size_t >::type ni(niSEXP);
    Rcpp::traits::input_parameter< size_t >::type nw(nwSEXP);
    rcpp_result_gen = Rcpp::wrap(C_AdjSD(z, X_full, na_rm, ni, nw));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_MultiscaleDEM_C_extract_window", (DL_FUNC) &_MultiscaleDEM_C_extract_window, 3},
    {"_MultiscaleDEM_subset_mat_rows", (DL_FUNC) &_MultiscaleDEM_subset_mat_rows, 2},
    {"_MultiscaleDEM_C_OLS_params", (DL_FUNC) &_MultiscaleDEM_C_OLS_params, 2},
    {"_MultiscaleDEM_C_OLS_resid", (DL_FUNC) &_MultiscaleDEM_C_OLS_resid, 2},
    {"_MultiscaleDEM_C_multiscale2", (DL_FUNC) &_MultiscaleDEM_C_multiscale2, 4},
    {"_MultiscaleDEM_C_multiscale1", (DL_FUNC) &_MultiscaleDEM_C_multiscale1, 4},
    {"_MultiscaleDEM_C_WoodEvans", (DL_FUNC) &_MultiscaleDEM_C_WoodEvans, 5},
    {"_MultiscaleDEM_C_AdjSD", (DL_FUNC) &_MultiscaleDEM_C_AdjSD, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_MultiscaleDEM(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
