# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

C_extract_window <- function(r, w, idx) {
    .Call(`_MultiscaleDEM_C_extract_window`, r, w, idx)
}

subset_mat_rows <- function(x, idx) {
    .Call(`_MultiscaleDEM_subset_mat_rows`, x, idx)
}

C_OLS_params <- function(X, Y) {
    .Call(`_MultiscaleDEM_C_OLS_params`, X, Y)
}

C_OLS_resid <- function(X, Y) {
    .Call(`_MultiscaleDEM_C_OLS_resid`, X, Y)
}

C_multiscale2 <- function(r, w, X, na_rm) {
    .Call(`_MultiscaleDEM_C_multiscale2`, r, w, X, na_rm)
}

C_multiscale1 <- function(r, w, X, na_rm) {
    .Call(`_MultiscaleDEM_C_multiscale1`, r, w, X, na_rm)
}

C_Multiscale2b <- function(z, X_full, na_rm, ni, nw) {
    .Call(`_MultiscaleDEM_C_Multiscale2b`, z, X_full, na_rm, ni, nw)
}

C_OLSraw2 <- function(y, X, ni, nw) {
    .Call(`_MultiscaleDEM_C_OLSraw2`, y, X, ni, nw)
}

