# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

C_AdjSD_narmT <- function(z, X_full, ni, nw) {
    .Call(`_MultiscaleDTM_C_AdjSD_narmT`, z, X_full, ni, nw)
}

C_AdjSD_narmF <- function(z, X, Xt, XtX_inv, ni, nw) {
    .Call(`_MultiscaleDTM_C_AdjSD_narmF`, z, X, Xt, XtX_inv, ni, nw)
}

C_CountVals <- function(z, ni, nw) {
    .Call(`_MultiscaleDTM_C_CountVals`, z, ni, nw)
}

C_Qfit1_narmT <- function(z, X_full, return_intercept, ni, nw) {
    .Call(`_MultiscaleDTM_C_Qfit1_narmT`, z, X_full, return_intercept, ni, nw)
}

C_Qfit1_narmF <- function(z, X, Xt, XtX_inv, return_intercept, ni, nw) {
    .Call(`_MultiscaleDTM_C_Qfit1_narmF`, z, X, Xt, XtX_inv, return_intercept, ni, nw)
}

C_Qfit2_narmT <- function(z, X_full, ni, nw) {
    .Call(`_MultiscaleDTM_C_Qfit2_narmT`, z, X_full, ni, nw)
}

C_Qfit2_narmF <- function(z, X, Xt, XtX_inv, ni, nw) {
    .Call(`_MultiscaleDTM_C_Qfit2_narmF`, z, X, Xt, XtX_inv, ni, nw)
}

C_TriArea <- function(a, b, c) {
    .Call(`_MultiscaleDTM_C_TriArea`, a, b, c)
}

C_SurfaceArea <- function(z, x_res, y_res, na_rm, ni, nw) {
    .Call(`_MultiscaleDTM_C_SurfaceArea`, z, x_res, y_res, na_rm, ni, nw)
}

